[modules]
deliver = [
    "file",
]

[file]
root_path = "repo"

[file.users]
"The teacher" = "teacher"
"Smart student" = "student"
"Beautiful student" = "studentka"

[tasks.first]
open_date = 2023-07-12
checks = {"The teacher:first/deadline" = [], "The teacher:first/attendance" = [], "The teacher:first/no_import" = [], "The teacher:first/solution_size" = [30, ]}

[tasks.second]
open_date = 2023-08-12
checks = {"The teacher:first/deadline" = [], "The teacher:first/attendance" = [], "The teacher:first/no_import" = [], "The teacher:first/solution_size" = [30, ]}

[score]
score_directory = "scores"
