[modules]
deliver = [
    "file",
]

[file]
root_path = "example"

[file.users]
"The teacher" = "teacher"
"Smart student" = "student"
"Beautiful student" = "studentka"

[tasks.first]
open_date =  2023-07-12

[tasks.second]
open_date =  2023-08-12

[score]
score_directory = "example_scores"