[logging]
"console level" = "INFO"
"file level" = "DEBUG"

[modules]
deliver = [
    "imap",
    "git",
    "file",
]

[git]
directory = "/tmp/hworker_git"

# list of users - repos
[git.users]
# user_ID = "repo"

[IMAP]
# host = "host"
port = "993"
# folder = "folder"
# username = "username"
# password = "password"
# letter_limit = -1

[IMAP.users]
# user_ID = "mail address"

[file]
root_path = "files"

[file.users]
# user_ID = "path"

[tasks]

[tasks.default]
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"

# [tasks.task_ID]
# deliver_ID = "20240101/01"
# open_date = 2024-01-01
# soft_deadline_delta = "open_date+8d"
# hard_deadline_delta = "open_date+15d"
# time_limit = 2
# resource_limit = 3145728
# checks = [
#    "check_name_1",
#    "check_name_2",
#    "...",
# ]
# comparison_type = "exact"

[check]
directory = "/tmp/hworker_check"

[check.default]
max_size = 100
default_time_limit = 2
default_resource_limit = 3145728

[formalization]
prog_name = "prog.py"
remotes_name = "remotes"
checks_dir = "checks"
checks_suffix = "in/out"