[logging]
"console level" = "INFO"
"file level" = "DEBUG"

[modules]
deliver = [
    "imap",
    "git",
    "file",
]

[git]
directory = "/tmp/hworker_git"

# list of users - repos
[git.users]
# user_ID = "repo"

[imap]
host = "host"
port = 993
folder = "folder"
username = "username"
password = "password"
letter_limit = -1

[imap.users]
# user_ID = "mail address"

[file]
root_path = "files"

[file.users]
# user_ID = "path"

[tasks]

[tasks._default]
soft_deadline_delta = "open_date+6d"
hard_deadline_delta = "open_date+13d"
test_size = 100
time_limit = 2
resource_limit = 3145728

# [tasks.task_ID]
# deliver_ID = "20240101/01"  # example, fill it
# open_date = "20240101"  # example, fill it
# soft_deadline = "20240108"  # example, fill it
# hard_deadline = "20240401"  # example, fill it
# time_limit = 2 # example, fill it
# resource_limit = 3145728  # optional field
# checks = [# optional field
#     "check_name_1",
#     "check_name_2",
#     "...",
# ]
# comparison_type = "exact"

[check]
directory = "/tmp/hworker_check"

[formalization]
prog_name = "prog.py"
remotes_name = "remotes"
checks_dir = "checks"
checks_suffix = "in/out"

[publish]
course_name = "Kapibarology"
secret_cookie = "kapibara"
