name: Pull request tests and build
run-name: ${{ github.actor }} pulling a request

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt
      - name: Unit tests
        run: python -m pytest tests
      - name: Build distributions
        run: python -m build -w
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }} wheel
          path: dist/*.whl
# TODO: install and run-test wheel
