name: serve-pull-request
run-name: ${{ github.actor }} pulling a request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest build
          pipenv lock
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt
      - name: Unit tests
        run: python -m pytest tests
      - name: Build distributions
        run: python -m build -w
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }} wheel
          path: dist/*.whl
# TODO: install and run-test wheel
