name: Tests
run-name: ${{ github.actor }} runs tests

on:
  workflow_call:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.11.4" ]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt
      - name: Unit tests
        run: python -m pytest tests
